# Configuration for dependabot that is activated on the github page for the repository.

version: 2
updates:
- package-ecosystem: pip
  directory: /
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: develop
  labels:
  - dependencies
