repos:
  - repo: https://github.com/mverteuil/precommit-dephell
    rev: master
    hooks:
      - id: dephell
  - repo: local
    hooks:
      - id: export-requirements
        name: Export requeriments.txt
        language: system
        pass_filenames: false
        entry: poetry export --without-hashes -o requirements.txt
        files: ^(pyproject.toml|poetry.lock)$