# This workflow will
# - draft a new release the next time a release is tagged.
#
# Uses the release-drafter.yml configuration file in the .github directory.
# https://github.com/marketplace/actions/release-drafter


name: Release Drafter

on:
  push:
    tags:
      - 'v*'

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "main"
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
