name: Create UML diagrams

on: [push]

jobs:
  uml:
    if: "contains(github.event.head_commit.message, '[uml]')"
    runs-on: ubuntu-latest
    steps:
    - name: Check-out the repository
      uses: actions/checkout@v2
    - name: Set up the Python environment
      uses: actions/setup-python@v2
      with:
          python-version: 3.7
    - name: Setup Pyreverse (part of Pylint)
      run: pip install pylint
    - name: Setup GraphViz
      uses: ts-graphviz/setup-graphviz@v1
    - name: Create UML diagrams (*.dot files)
      run: pyreverse -Amy -p ${{ github.event.repository.name }} Base/
    - name: Create UML diagrams (*.pdf files)
      run: |
        dot -Tpdf packages_${{ github.event.repository.name }}.dot -o packages_${{ github.event.repository.name }}.pdf
        dot -Tpdf classes_${{ github.event.repository.name }}.dot -o classes_${{ github.event.repository.name }}.pdf
    - name: Move UML diagrams
      run: mv *.dot *.pdf Diagrams/
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update UML diagrams
